# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pprescripts.ui'
#
# Created: Fri Aug 27 16:57:15 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_scriptDlg(object):
    def setupUi(self, scriptDlg):
        scriptDlg.setObjectName("scriptDlg")
        scriptDlg.resize(1036, 658)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("PPRE.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        scriptDlg.setWindowIcon(icon)
        self.chooseScript = QtGui.QComboBox(scriptDlg)
        self.chooseScript.setGeometry(QtCore.QRect(110, 10, 151, 26))
        self.chooseScript.setObjectName("chooseScript")
        self.scriptLabel = QtGui.QLabel(scriptDlg)
        self.scriptLabel.setGeometry(QtCore.QRect(10, 20, 101, 18))
        self.scriptLabel.setObjectName("scriptLabel")
        self.mapTab = QtGui.QTabWidget(scriptDlg)
        self.mapTab.setGeometry(QtCore.QRect(10, 50, 974, 584))
        self.mapTab.setObjectName("mapTab")
        self.scriptTab = QtGui.QWidget()
        self.scriptTab.setObjectName("scriptTab")
        self.tabWidget = QtGui.QTabWidget(self.scriptTab)
        self.tabWidget.setGeometry(QtCore.QRect(344, 10, 609, 529))
        self.tabWidget.setObjectName("tabWidget")
        self.scriptEditTab = QtGui.QWidget()
        self.scriptEditTab.setObjectName("scriptEditTab")
        self.scriptTabWidget = QtGui.QTabWidget(self.scriptEditTab)
        self.scriptTabWidget.setGeometry(QtCore.QRect(26, 44, 557, 433))
        self.scriptTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.scriptTabWidget.setObjectName("scriptTabWidget")
        self.scr_1 = QtGui.QWidget()
        self.scr_1.setObjectName("scr_1")
        self.textBrowser = QtGui.QTextBrowser(self.scr_1)
        self.textBrowser.setGeometry(QtCore.QRect(24, 24, 513, 345))
        self.textBrowser.setUndoRedoEnabled(True)
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName("textBrowser")
        self.scriptTabWidget.addTab(self.scr_1, "")
        self.scr_2 = QtGui.QWidget()
        self.scr_2.setObjectName("scr_2")
        self.scriptTabWidget.addTab(self.scr_2, "")
        self.addScriptButton = QtGui.QPushButton(self.scriptEditTab)
        self.addScriptButton.setGeometry(QtCore.QRect(24, 6, 103, 27))
        self.addScriptButton.setObjectName("addScriptButton")
        self.tabWidget.addTab(self.scriptEditTab, "")
        self.functionTab = QtGui.QWidget()
        self.functionTab.setObjectName("functionTab")
        self.funcTabWidget = QtGui.QTabWidget(self.functionTab)
        self.funcTabWidget.setGeometry(QtCore.QRect(12, 52, 557, 425))
        self.funcTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.funcTabWidget.setObjectName("funcTabWidget")
        self.func_1 = QtGui.QWidget()
        self.func_1.setObjectName("func_1")
        self.funcTabWidget.addTab(self.func_1, "")
        self.func_2 = QtGui.QWidget()
        self.func_2.setObjectName("func_2")
        self.funcTabWidget.addTab(self.func_2, "")
        self.addFunctionButton = QtGui.QPushButton(self.functionTab)
        self.addFunctionButton.setGeometry(QtCore.QRect(10, 8, 99, 27))
        self.addFunctionButton.setObjectName("addFunctionButton")
        self.tabWidget.addTab(self.functionTab, "")
        self.movTab = QtGui.QWidget()
        self.movTab.setObjectName("movTab")
        self.movTabWidget = QtGui.QTabWidget(self.movTab)
        self.movTabWidget.setGeometry(QtCore.QRect(16, 46, 557, 429))
        self.movTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.movTabWidget.setObjectName("movTabWidget")
        self.mov_1 = QtGui.QWidget()
        self.mov_1.setObjectName("mov_1")
        self.movTabWidget.addTab(self.mov_1, "")
        self.mov_2 = QtGui.QWidget()
        self.mov_2.setObjectName("mov_2")
        self.movTabWidget.addTab(self.mov_2, "")
        self.addMovementButton_2 = QtGui.QPushButton(self.movTab)
        self.addMovementButton_2.setGeometry(QtCore.QRect(14, 6, 127, 27))
        self.addMovementButton_2.setObjectName("addMovementButton_2")
        self.tabWidget.addTab(self.movTab, "")
        self.variableTab = QtGui.QWidget()
        self.variableTab.setObjectName("variableTab")
        self.tabWidget_6 = QtGui.QTabWidget(self.variableTab)
        self.tabWidget_6.setGeometry(QtCore.QRect(26, 10, 393, 479))
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.varTab = QtGui.QWidget()
        self.varTab.setObjectName("varTab")
        self.varList = QtGui.QTableWidget(self.varTab)
        self.varList.setGeometry(QtCore.QRect(14, 8, 159, 429))
        self.varList.setObjectName("varList")
        self.varList.setColumnCount(1)
        self.varList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.varList.setHorizontalHeaderItem(0, item)
        self.tabWidget_6.addTab(self.varTab, "")
        self.flagList = QtGui.QWidget()
        self.flagList.setObjectName("flagList")
        self.varList_2 = QtGui.QTableWidget(self.flagList)
        self.varList_2.setGeometry(QtCore.QRect(12, 12, 159, 429))
        self.varList_2.setObjectName("varList_2")
        self.varList_2.setColumnCount(1)
        self.varList_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.varList_2.setHorizontalHeaderItem(0, item)
        self.tabWidget_6.addTab(self.flagList, "")
        self.localList = QtGui.QWidget()
        self.localList.setObjectName("localList")
        self.varList_3 = QtGui.QTableWidget(self.localList)
        self.varList_3.setGeometry(QtCore.QRect(20, 16, 159, 429))
        self.varList_3.setObjectName("varList_3")
        self.varList_3.setColumnCount(1)
        self.varList_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.varList_3.setHorizontalHeaderItem(0, item)
        self.tabWidget_6.addTab(self.localList, "")
        self.tabWidget.addTab(self.variableTab, "")
        self.scriptOrdTab = QtGui.QWidget()
        self.scriptOrdTab.setObjectName("scriptOrdTab")
        self.scriptOrdList = QtGui.QListWidget(self.scriptOrdTab)
        self.scriptOrdList.setGeometry(QtCore.QRect(76, 32, 256, 331))
        self.scriptOrdList.setDragEnabled(True)
        self.scriptOrdList.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.scriptOrdList.setFlow(QtGui.QListView.TopToBottom)
        self.scriptOrdList.setObjectName("scriptOrdList")
        QtGui.QListWidgetItem(self.scriptOrdList)
        self.tabWidget.addTab(self.scriptOrdTab, "")
        self.compileTab = QtGui.QWidget()
        self.compileTab.setObjectName("compileTab")
        self.compileOutput = QtGui.QTextEdit(self.compileTab)
        self.compileOutput.setGeometry(QtCore.QRect(10, 64, 587, 419))
        self.compileOutput.setReadOnly(True)
        self.compileOutput.setObjectName("compileOutput")
        self.clearCompile = QtGui.QPushButton(self.compileTab)
        self.clearCompile.setGeometry(QtCore.QRect(204, 14, 155, 27))
        self.clearCompile.setObjectName("clearCompile")
        self.tabWidget.addTab(self.compileTab, "")
        self.tabWidget_3 = QtGui.QTabWidget(self.scriptTab)
        self.tabWidget_3.setGeometry(QtCore.QRect(6, 104, 325, 433))
        self.tabWidget_3.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.navScripts = QtGui.QWidget()
        self.navScripts.setObjectName("navScripts")
        self.navScript = QtGui.QTreeWidget(self.navScripts)
        self.navScript.setGeometry(QtCore.QRect(18, 6, 267, 389))
        self.navScript.setIndentation(10)
        self.navScript.setObjectName("navScript")
        item_0 = QtGui.QTreeWidgetItem(self.navScript)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.navScript.header().setCascadingSectionResizes(True)
        self.navScript.header().setDefaultSectionSize(80)
        self.navScript.header().setHighlightSections(False)
        self.navScript.header().setSortIndicatorShown(True)
        self.tabWidget_3.addTab(self.navScripts, "")
        self.navFunctions = QtGui.QWidget()
        self.navFunctions.setObjectName("navFunctions")
        self.navFunc = QtGui.QTreeWidget(self.navFunctions)
        self.navFunc.setGeometry(QtCore.QRect(18, 8, 267, 391))
        self.navFunc.setIndentation(10)
        self.navFunc.setObjectName("navFunc")
        item_0 = QtGui.QTreeWidgetItem(self.navFunc)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_0 = QtGui.QTreeWidgetItem(self.navFunc)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.navFunc)
        self.navFunc.header().setCascadingSectionResizes(True)
        self.navFunc.header().setDefaultSectionSize(80)
        self.navFunc.header().setHighlightSections(False)
        self.navFunc.header().setSortIndicatorShown(True)
        self.tabWidget_3.addTab(self.navFunctions, "")
        self.navMovements = QtGui.QWidget()
        self.navMovements.setObjectName("navMovements")
        self.navMov = QtGui.QTreeWidget(self.navMovements)
        self.navMov.setGeometry(QtCore.QRect(16, 8, 271, 389))
        self.navMov.setIndentation(10)
        self.navMov.setObjectName("navMov")
        item_0 = QtGui.QTreeWidgetItem(self.navMov)
        self.navMov.header().setCascadingSectionResizes(True)
        self.navMov.header().setDefaultSectionSize(80)
        self.navMov.header().setHighlightSections(False)
        self.navMov.header().setSortIndicatorShown(True)
        self.tabWidget_3.addTab(self.navMovements, "")
        self.updateNav = QtGui.QPushButton(self.scriptTab)
        self.updateNav.setGeometry(QtCore.QRect(74, 10, 217, 27))
        self.updateNav.setObjectName("updateNav")
        self.gotoError = QtGui.QPushButton(self.scriptTab)
        self.gotoError.setEnabled(False)
        self.gotoError.setGeometry(QtCore.QRect(74, 40, 215, 27))
        self.gotoError.setObjectName("gotoError")
        self.checkBox = QtGui.QCheckBox(self.scriptTab)
        self.checkBox.setGeometry(QtCore.QRect(74, 70, 215, 22))
        self.checkBox.setObjectName("checkBox")
        self.mapTab.addTab(self.scriptTab, "")

        self.retranslateUi(scriptDlg)
        self.mapTab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(3)
        self.scriptTabWidget.setCurrentIndex(0)
        self.funcTabWidget.setCurrentIndex(0)
        self.movTabWidget.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QObject.connect(self.chooseScript, QtCore.SIGNAL("currentIndexChanged(int)"), scriptDlg.updateScript)
        QtCore.QObject.connect(self.clearCompile, QtCore.SIGNAL("clicked()"), self.compileOutput.clear)
        QtCore.QObject.connect(self.updateNav, QtCore.SIGNAL("clicked()"), scriptDlg.compile)
        QtCore.QObject.connect(self.addScriptButton, QtCore.SIGNAL("clicked()"), scriptDlg.addScript)
        QtCore.QObject.connect(self.gotoError, QtCore.SIGNAL("clicked()"), scriptDlg.gotoCompileOutput)
        QtCore.QObject.connect(self.navScript, QtCore.SIGNAL("itemDoubleClicked(QTreeWidgetItem*,int)"), scriptDlg.gotoNavScript)
        QtCore.QObject.connect(self.navFunc, QtCore.SIGNAL("itemDoubleClicked(QTreeWidgetItem*,int)"), scriptDlg.gotoNavFunc)
        QtCore.QObject.connect(self.navMov, QtCore.SIGNAL("itemDoubleClicked(QTreeWidgetItem*,int)"), scriptDlg.gotoNavMov)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL("clicked(bool)"), scriptDlg.navigatorMode)
        QtCore.QObject.connect(self.addFunctionButton, QtCore.SIGNAL("clicked()"), scriptDlg.addFunction)
        QtCore.QObject.connect(self.addMovementButton_2, QtCore.SIGNAL("clicked()"), scriptDlg.addMovement)
        QtCore.QMetaObject.connectSlotsByName(scriptDlg)

    def retranslateUi(self, scriptDlg):
        scriptDlg.setWindowTitle(QtGui.QApplication.translate("scriptDlg", "Script Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.scriptLabel.setText(QtGui.QApplication.translate("scriptDlg", "Script Number", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("scriptDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"script://1\"><span style=\" text-decoration: underline; color:#0000ff;\">script 1</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.scriptTabWidget.setTabText(self.scriptTabWidget.indexOf(self.scr_1), QtGui.QApplication.translate("scriptDlg", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.scriptTabWidget.setTabText(self.scriptTabWidget.indexOf(self.scr_2), QtGui.QApplication.translate("scriptDlg", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.addScriptButton.setText(QtGui.QApplication.translate("scriptDlg", "Add Script", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scriptEditTab), QtGui.QApplication.translate("scriptDlg", "Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.funcTabWidget.setTabText(self.funcTabWidget.indexOf(self.func_1), QtGui.QApplication.translate("scriptDlg", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.funcTabWidget.setTabText(self.funcTabWidget.indexOf(self.func_2), QtGui.QApplication.translate("scriptDlg", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.addFunctionButton.setText(QtGui.QApplication.translate("scriptDlg", "Add Function", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.functionTab), QtGui.QApplication.translate("scriptDlg", "Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.movTabWidget.setTabText(self.movTabWidget.indexOf(self.mov_1), QtGui.QApplication.translate("scriptDlg", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.movTabWidget.setTabText(self.movTabWidget.indexOf(self.mov_2), QtGui.QApplication.translate("scriptDlg", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.addMovementButton_2.setText(QtGui.QApplication.translate("scriptDlg", "Add Movement", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.movTab), QtGui.QApplication.translate("scriptDlg", "Movements", None, QtGui.QApplication.UnicodeUTF8))
        self.varList.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("scriptDlg", "Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.varTab), QtGui.QApplication.translate("scriptDlg", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.varList_2.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("scriptDlg", "Flag", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.flagList), QtGui.QApplication.translate("scriptDlg", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.varList_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("scriptDlg", "Local Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.localList), QtGui.QApplication.translate("scriptDlg", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.variableTab), QtGui.QApplication.translate("scriptDlg", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.scriptOrdList.isSortingEnabled()
        self.scriptOrdList.setSortingEnabled(False)
        self.scriptOrdList.item(0).setText(QtGui.QApplication.translate("scriptDlg", "Script 1", None, QtGui.QApplication.UnicodeUTF8))
        self.scriptOrdList.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scriptOrdTab), QtGui.QApplication.translate("scriptDlg", "Orders", None, QtGui.QApplication.UnicodeUTF8))
        self.clearCompile.setText(QtGui.QApplication.translate("scriptDlg", "Clear Output", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.compileTab), QtGui.QApplication.translate("scriptDlg", "Compiler Output", None, QtGui.QApplication.UnicodeUTF8))
        self.navScript.headerItem().setText(0, QtGui.QApplication.translate("scriptDlg", "Navigation", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.navScript.isSortingEnabled()
        self.navScript.setSortingEnabled(False)
        self.navScript.topLevelItem(0).setText(0, QtGui.QApplication.translate("scriptDlg", "Script 1", None, QtGui.QApplication.UnicodeUTF8))
        self.navScript.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("scriptDlg", "Function 1", None, QtGui.QApplication.UnicodeUTF8))
        self.navScript.topLevelItem(0).child(0).child(0).setText(0, QtGui.QApplication.translate("scriptDlg", "Function 2", None, QtGui.QApplication.UnicodeUTF8))
        self.navScript.topLevelItem(0).child(0).child(1).setText(0, QtGui.QApplication.translate("scriptDlg", "Movement 1", None, QtGui.QApplication.UnicodeUTF8))
        self.navScript.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("scriptDlg", "Function 3", None, QtGui.QApplication.UnicodeUTF8))
        self.navScript.setSortingEnabled(__sortingEnabled)
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.navScripts), QtGui.QApplication.translate("scriptDlg", "Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.navFunc.headerItem().setText(0, QtGui.QApplication.translate("scriptDlg", "Navigation", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.navFunc.isSortingEnabled()
        self.navFunc.setSortingEnabled(False)
        self.navFunc.topLevelItem(0).setText(0, QtGui.QApplication.translate("scriptDlg", "Function 1", None, QtGui.QApplication.UnicodeUTF8))
        self.navFunc.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("scriptDlg", "Function 2", None, QtGui.QApplication.UnicodeUTF8))
        self.navFunc.topLevelItem(0).child(0).child(0).setText(0, QtGui.QApplication.translate("scriptDlg", "Movement 1", None, QtGui.QApplication.UnicodeUTF8))
        self.navFunc.topLevelItem(1).setText(0, QtGui.QApplication.translate("scriptDlg", "Function 2", None, QtGui.QApplication.UnicodeUTF8))
        self.navFunc.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("scriptDlg", "Movement 1", None, QtGui.QApplication.UnicodeUTF8))
        self.navFunc.topLevelItem(2).setText(0, QtGui.QApplication.translate("scriptDlg", "Function 3", None, QtGui.QApplication.UnicodeUTF8))
        self.navFunc.setSortingEnabled(__sortingEnabled)
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.navFunctions), QtGui.QApplication.translate("scriptDlg", "Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.navMov.headerItem().setText(0, QtGui.QApplication.translate("scriptDlg", "Navigation", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.navMov.isSortingEnabled()
        self.navMov.setSortingEnabled(False)
        self.navMov.topLevelItem(0).setText(0, QtGui.QApplication.translate("scriptDlg", "Movement 1", None, QtGui.QApplication.UnicodeUTF8))
        self.navMov.setSortingEnabled(__sortingEnabled)
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.navMovements), QtGui.QApplication.translate("scriptDlg", "Movements", None, QtGui.QApplication.UnicodeUTF8))
        self.updateNav.setText(QtGui.QApplication.translate("scriptDlg", "Update Navigator / Compile", None, QtGui.QApplication.UnicodeUTF8))
        self.gotoError.setText(QtGui.QApplication.translate("scriptDlg", "Go To Errors (0) / Warnings (0)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("scriptDlg", "Navigator Mode (Read Only)", None, QtGui.QApplication.UnicodeUTF8))
        self.mapTab.setTabText(self.mapTab.indexOf(self.scriptTab), QtGui.QApplication.translate("scriptDlg", "Scripts", None, QtGui.QApplication.UnicodeUTF8))

